//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson()
        {
            this.session = new HashSet<session>();
            this.student_lesson = new HashSet<student_lesson>();
        }
    
        public int lesson_id { get; set; }
        public string lesson_name { get; set; }
        public Nullable<int> departmant_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<System.TimeSpan> lesson_onset_time { get; set; }
        public Nullable<System.TimeSpan> lesson_expiration_time { get; set; }
    
        public virtual departmant departmant { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session> session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_lesson> student_lesson { get; set; }
    }
}
