//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class barkode_projectEntities : DbContext
    {
        public barkode_projectEntities()
            : base("name=barkode_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barcode> barcode { get; set; }
        public virtual DbSet<departmant> departmant { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<lesson> lesson { get; set; }
        public virtual DbSet<session> session { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<student_lesson> student_lesson { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<rate> rate { get; set; }
    }
}
