//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deneme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session()
        {
            this.history = new HashSet<history>();
        }
    
        public int session_id { get; set; }
        public Nullable<int> lesson_id { get; set; }
        public int barcode_id { get; set; }
        public string session_content { get; set; }
        public Nullable<System.DateTime> session_onset_time { get; set; }
        public Nullable<System.DateTime> session_expiration_time { get; set; }
    
        public virtual barcode barcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> history { get; set; }
        public virtual lesson lesson { get; set; }
    }
}
